### ISSUE TITLE
The website crashes and reloads upon opening a popup

### ISSUE THREAD

**Issue by kilimanj4r0** [one-zero-eight/website#141]
### Describe the bug

Clicking on an event in any calendar opens a popup that can become stuck, preventing closure. Additionally, it crashes the website and reloads the page within 1-2 seconds.

### Your device details

Desktop, Linux, Yandex Browser 24.6.1.852 stable (64-bit)

### Reproduction

1. Go to https://innohassle.ru/schedule
2. Open any schedule
3. Open any group
4. Click on any event in any form of calendar
5. Wait 1-2 seconds
6. Website crashes and reloads the page

### Screenshots / Additional context

![image](https://github.com/user-attachments/assets/426fd5bc-ede6-4d78-9ac2-fa6e3859e29b)
![image](https://github.com/user-attachments/assets/cefe34ed-9f85-4f8e-8850-31276387fcdf)

**Comment by ArtemSBulgakov** [comment]
Thank you for the issue!

Something wrong with Yandex Browser for Linux. Other websites may crash sometimes too (try hovering over any card [here](https://daisyui.com/components/)). No such issue on Yandex Browser for Windows.

Do you have any idea of the reason of the crash?

**Comment by kilimanj4r0** [comment]
The same crash occurs on the website you provided. I recommend contacting Yandex Browser support.

**Comment by ArtemSBulgakov** [comment]
@kilimanj4r0 Please check the issue with a new version of Yandex Browser. I do not have such problem since I've upgraded the browser to v24.7.1.1120 (you can see the version on `browser://help/` page).

**Comment by kilimanj4r0** [comment]
@ArtemSBulgakov Seems there is no more this issue, thanks! However, I found that popup resets its position (top-left, see the screenshot) when switching the format of calendar (e.g., 3 days to week).
![image](https://github.com/user-attachments/assets/725a099f-2522-45e7-90e7-6421c178633d)

**Comment by ArtemSBulgakov** [comment]
Should be fixed by 16bd4ae3. You can verify on staging website: https://pre.innohassle.ru/dashboard.
