### ISSUE TITLE
[Room-Booking] Implement light theme

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/website#150]
### Describe the feature

Currently there is only dark theme, however our main website supports both dark and light theme.

### Suggested solution

Change colors based on 'dark' class of parent elements.

**Comment by evermake** [comment]
@ArtemSBulgakov, implemented in https://github.com/evermake/innoversity/commit/f5c0a2b4a1e0f317ff2d45aa6bad1369a5c66b55

**Comment by ArtemSBulgakov** [comment]
@evermake You can push it to one-zero-eight/website

**Comment by evermake** [comment]
@ArtemSBulgakov made it in https://github.com/one-zero-eight/website/commit/b54d6172b7fd0aafa03a619f4548741baae52312
