### ISSUE TITLE
[Room-Booking] Do not allow to book auditoriums during day-time and in the past

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/website#154]
### Describe the feature

Students are not allowed to book auditoriums from 8:00 to 19:00 during Monday-Friday.

"You can book lecture room from 19:00 to 8:00 next day on working days"

### Suggested solution

We should show which time is unavailable, and prevent booking during these time slots.

**Comment by ArtemSBulgakov** [comment]
Also: show somehow that you cannot book in the past

**Comment by evermake** [comment]
Moved to #162.
