### ISSUE TITLE
Redesign the request to Sign In

### ISSUE THREAD

**Issue by danmaninc** [one-zero-eight/website#60]
When user is not authorized, the popup appears. For now, this popup shows only the text.

- [ ] Add the image to the pop-up to make it more attractive
- [ ] Add the image to the Dashboard page to make it more attractive

**Comment by ArtemSBulgakov** [comment]
![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/44732506/e0725a0f-28a8-4eba-977d-9b32037d8662)

Может быть, добавить картинок; больше описания
