### ISSUE TITLE
Make more pretty "How it works" section

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/website#90]
### Describe the feature

The current Schedule page shows a general information about how the service works. It is somehow outdated, and not useful.

### Suggested solution

Redesign the section (or maybe the whole page).

### Additional context

Current state:

![Image](https://github.com/one-zero-eight/InNoHassle-Website/assets/44732506/ba740406-c1a0-450e-9953-00fab877d4bd)

**Comment by ArtemSBulgakov** [comment]
Может быть назвать "How you can use it".
Может быть добавить инструкцию по использованию.

**Comment by ArtemSBulgakov** [comment]
Пофиксить адаптивную верстку этого раздела

**Comment by evermake** [comment]
I think this is not relevant since we're planning to re-design everything, what do you think, @ArtemSBulgakov?
